name: final_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5
  webview_flutter: ^4.0.0
  url_launcher: ^6.2.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.0
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  fl_chart: ^0.68.0
  connectivity_plus: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.1.5
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/full_body.jpeg
    - assets/plank.jpg
    - assets/fit15.jpeg
    - assets/cardio.jpg
    - assets/chest_workout.jpeg
    - assets/leg_workout.jpeg
    - assets/back_workout.jpg
    - assets/abs.jpg
    - assets/arms.jpg
    - assets/push-ups.jpeg
    - assets/squat.jpg
    - assets/planet_fitness.jpg
    - assets/golden_gym.jpg
    - assets/profile.jpg


