// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RHRUhkepNGgbndWZ-YYGcOnmS3sd8Yk',
    appId: '1:168898118838:web:6f2fef46834efdde66d217',
    messagingSenderId: '168898118838',
    projectId: 'myfitnesspal-85e8f',
    authDomain: 'myfitnesspal-85e8f.firebaseapp.com',
    storageBucket: 'myfitnesspal-85e8f.firebasestorage.app',
    measurementId: 'G-8ZNVPNKG78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxfxoITFud1KYGOzurGf8f5tCqT7p3NNg',
    appId: '1:168898118838:android:3da8128b1675f19966d217',
    messagingSenderId: '168898118838',
    projectId: 'myfitnesspal-85e8f',
    storageBucket: 'myfitnesspal-85e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAin-hp1fcswJF5xY4REPMrXNv0GgztgNI',
    appId: '1:168898118838:ios:5ec6c73aaf7b7e4566d217',
    messagingSenderId: '168898118838',
    projectId: 'myfitnesspal-85e8f',
    storageBucket: 'myfitnesspal-85e8f.firebasestorage.app',
    iosBundleId: 'com.example.final3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAin-hp1fcswJF5xY4REPMrXNv0GgztgNI',
    appId: '1:168898118838:ios:5ec6c73aaf7b7e4566d217',
    messagingSenderId: '168898118838',
    projectId: 'myfitnesspal-85e8f',
    storageBucket: 'myfitnesspal-85e8f.firebasestorage.app',
    iosBundleId: 'com.example.final3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RHRUhkepNGgbndWZ-YYGcOnmS3sd8Yk',
    appId: '1:168898118838:web:f5224eb9171befef66d217',
    messagingSenderId: '168898118838',
    projectId: 'myfitnesspal-85e8f',
    authDomain: 'myfitnesspal-85e8f.firebaseapp.com',
    storageBucket: 'myfitnesspal-85e8f.firebasestorage.app',
    measurementId: 'G-MDN0D3S6JK',
  );
}
